name       : strawberry
version    : 0.6.13
release    : 20
source     :
    - https://github.com/strawberrymusicplayer/strawberry/archive/0.6.13.tar.gz : d0865277af03afc8b5232e697599ad09058e0fef292860abe94c8012b01da1b2
license    : GPL-3.0-or-later
homepage   : https://www.strawberrymusicplayer.org
component  : multimedia.audio
summary    : Strawberry is a audio player and music collection organizer.
description: |
    Strawberry is a audio player and music collection organizer. It is a fork of Clementine released in 2018 aimed at music collectors, audio enthusiasts and audiophiles.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(libcdio)
    - pkgconfig(libchromaprint)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(libusbmuxd-2.0)
    - pkgconfig(libpulse)
    - pkgconfig(protobuf)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
    - libboost-devel
    - liblastfm-devel
setup      : |
    %cmake_ninja -DUSE_SYSTEM_TAGLIB=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
