name       : strawberry
version    : 0.6.3
release    : 6
source     :
    - https://github.com/jonaski/strawberry/archive/0.6.3.tar.gz : 9ea31a404cfe71a4adfc236cb64133fe3c6033cfc0355ea475aa6935f51627ab
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Strawberry is a audio player and music collection organizer.
description: |
    Strawberry is a audio player and music collection organizer. It is a fork of Clementine released in 2018 aimed at music collectors, audio enthusiasts and audiophiles.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(libchromaprint)
    - pkgconfig(libcdio)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(libplist)
    - pkgconfig(libmtp)
    - pkgconfig(libpulse)
    - pkgconfig(libvlc)
    - pkgconfig(phonon4qt5)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
    - libboost-devel
    - liblastfm-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
