name       : strawberry
version    : 0.5.2
release    : 2
source     :
    - https://github.com/jonaski/strawberry/archive/0.5.2.tar.gz : 7fec87cb54d064bf6d40e0d4ceb21d9752c490b001c3cf28d774dc6105e7c861
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Strawberry is a audio player and music collection organizer.
description: |
    Strawberry is a audio player and music collection organizer. It is a fork of Clementine released in 2018 aimed at music collectors, audio enthusiasts and audiophiles.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libchromaprint)
    - pkgconfig(libcdio)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(libplist)
    - pkgconfig(libmtp)
    - pkgconfig(libpulse)
    - pkgconfig(libvlc)
    - pkgconfig(phonon4qt5)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
    - libboost-devel
    - liblastfm-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
