name       : strawberry
version    : 1.0.2
release    : 35
source     :
    - https://github.com/strawberrymusicplayer/strawberry/releases/download/1.0.2/strawberry-1.0.2.tar.xz : f5f0f754b88aa0f3860fb7d2adaba26d51fa64a32d1e202814600601a8a86d97
license    : GPL-3.0-or-later
homepage   : https://www.strawberrymusicplayer.org
component  : multimedia.audio
summary    : Strawberry is a audio player and music collection organizer.
description: |
    Strawberry is a audio player and music collection organizer. It is a fork of Clementine released in 2018 aimed at music collectors, audio enthusiasts and audiophiles.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(libcdio)
    - pkgconfig(libchromaprint)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(libpulse)
    - pkgconfig(protobuf)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - pkgconfig(Qt6UiTools)
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
    - libboost-devel
    - liblastfm-devel
setup      : |
    %cmake_ninja -DINSTALL_TRANSLATIONS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
