name       : strawberry
version    : 1.0.8
release    : 43
source     :
    - https://github.com/strawberrymusicplayer/strawberry/releases/download/1.0.8/strawberry-1.0.8.tar.xz : f6b8a267fc9ea366eb44b8c90c777a93e3d104bf29be38b5f72d565079e05024
license    : GPL-3.0-or-later
homepage   : https://www.strawberrymusicplayer.org
component  : multimedia.audio
summary    : Strawberry is a audio player and music collection organizer.
description: |
    Strawberry is a audio player and music collection organizer. It is a fork of Clementine released in 2018 aimed at music collectors, audio enthusiasts and audiophiles.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(icu-i18n)
    - pkgconfig(libcdio)
    - pkgconfig(libchromaprint)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(libpulse)
    - pkgconfig(protobuf)
    - pkgconfig(Qt6UiTools)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
    - libboost-devel
    - liblastfm-devel

setup      : |
    %cmake_ninja -DINSTALL_TRANSLATIONS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
