name       : strawberry
version    : 1.0.0
release    : 33
source     :
    - https://github.com/strawberrymusicplayer/strawberry/releases/download/1.0.0/strawberry-1.0.0.tar.xz : 21e1fb70f03450a6b9777d0afb271a7a7922258ebb364c86b8104327496ca7a1
license    : GPL-3.0-or-later
homepage   : https://www.strawberrymusicplayer.org
component  : multimedia.audio
summary    : Strawberry is a audio player and music collection organizer.
description: |
    Strawberry is a audio player and music collection organizer. It is a fork of Clementine released in 2018 aimed at music collectors, audio enthusiasts and audiophiles.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(libcdio)
    - pkgconfig(libchromaprint)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(libpulse)
    - pkgconfig(protobuf)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - pkgconfig(Qt6UiTools)
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
    - libboost-devel
    - liblastfm-devel
setup      : |
    %patch -p1 < $pkgfiles/Fix-stop-after-this-track-button-with-qt6.patch
    %cmake_ninja -DINSTALL_TRANSLATIONS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
