name       : strawberry
version    : 0.6.11
release    : 16
source     :
    - https://github.com/strawberrymusicplayer/strawberry/archive/0.6.11.tar.gz : c0d77f76c77dea9b149a5de107536d2617fd3df875b0e50bef434f88125117f8
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Strawberry is a audio player and music collection organizer.
description: |
    Strawberry is a audio player and music collection organizer. It is a fork of Clementine released in 2018 aimed at music collectors, audio enthusiasts and audiophiles.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(libcdio)
    - pkgconfig(libchromaprint)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(libplist)
    - pkgconfig(libpulse)
    - pkgconfig(protobuf)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
    - libboost-devel
    - liblastfm-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
