name       : strawberry
version    : 1.0.10
release    : 46
source     :
    - https://github.com/strawberrymusicplayer/strawberry/releases/download/1.0.10/strawberry-1.0.10.tar.xz : 47e6d707f5b24e960dfdac1752455fcd5733fbb194d43fd946d4d021d64867af
license    : GPL-3.0-or-later
homepage   : https://www.strawberrymusicplayer.org
component  : multimedia.audio
summary    : Strawberry is a audio player and music collection organizer.
description: |
    Strawberry is a audio player and music collection organizer. It is a fork of Clementine released in 2018 aimed at music collectors, audio enthusiasts and audiophiles.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(icu-i18n)
    - pkgconfig(libcdio)
    - pkgconfig(libchromaprint)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(libpulse)
    - pkgconfig(protobuf)
    - pkgconfig(Qt6UiTools)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
    - libboost-devel
    - liblastfm-devel

setup      : |
    %cmake_ninja -DINSTALL_TRANSLATIONS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
