name       : strawberry
version    : 0.5.5
release    : 5
source     :
    - https://github.com/jonaski/strawberry/archive/0.5.5.tar.gz : 16899fff239e6ce45e9a1e195133addf1ab982c738b387345bc54f328991b58c
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Strawberry is a audio player and music collection organizer.
description: |
    Strawberry is a audio player and music collection organizer. It is a fork of Clementine released in 2018 aimed at music collectors, audio enthusiasts and audiophiles.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(libchromaprint)
    - pkgconfig(libcdio)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(libplist)
    - pkgconfig(libmtp)
    - pkgconfig(libpulse)
    - pkgconfig(libvlc)
    - pkgconfig(phonon4qt5)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
    - libboost-devel
    - liblastfm-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
